### ISSUE TITLE
Macro to derive ordering for case class

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1054]
@jcoveney 

What we want is this:

case class MyClass(name: String, age: Int)

object MyClass {
  def ordering = deriveOrdering[MyClass]
  def monoid = deriveMonoid[MyClass]
}

**Comment by Trevoke** [comment]
@jcoveney Is it tomorrow yet?

**Comment by johnynek** [comment]
This was done.

See this wiki page here:
https://github.com/twitter/scalding/wiki/Automatic-Orderings%2C-Monoids-and-Arbitraries

**Comment by Trevoke** [comment]
Thanks :)
