### ISSUE TITLE
Move summingbird LookupJoin implementation to scalding

### ISSUE THREAD

**Issue by isnotinvain** [twitter/scalding#1121]
The two implementations have diverged but the SB one has more features, we should just move the SB lookup join to scalding and have SB use that.

**Comment by declerambaul** [comment]
Is the SB version of the LookupJoin stable? From a brief look it might be as easy as to copy the code to a package. In the meantime I would like to add a reducer option to the scalding version - I have forgotten to set the global reducer config one too many times.

**Comment by isnotinvain** [comment]
according to @ianoc the one in SB just went through some more changes, so maybe not quite stable yet.

**Comment by johnynek** [comment]
The code was changed to be a bit more clear, but I think we have tests on it, so I am not worried about correctness.

**Comment by isnotinvain** [comment]
by stable I meant 'not changing often' -- I think @ianoc has said that if it needs frequent changes moving it to scalding will be a pain for summingbird development. So if we think the code won't need to be changed often to support summingbird, then we can move it.

**Comment by johnynek** [comment]
Yeah, that's the conclusion we came to before. Putting this with scalding is a pain since it is really used in summingbird. I don't see periodic backports as a disaster.

**Comment by johnynek** [comment]
That said, I don't think summingbird-scalding depends on anything but summingbird-core and scalding. So, maybe we should just encourage people to use that.

**Comment by isnotinvain** [comment]
that will get funky when / if SB depends on an older version of scalding... does that ever happen?

**Comment by johnynek** [comment]
it is never older than the one we have in production at Twitter. But yes,
you could imagine scalding advancing beyond summingbird.

On Wed, Jan 14, 2015 at 2:15 PM, Alex Levenson <notifications@github.com>
wrote:

> that will get funky when / if SB depends on an older version of
> scalding... does that ever happen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1121#issuecomment-70018807>.
>



-- 
Oscar Boykin :: @posco :: http://twitter.com/posco
