### ISSUE TITLE
Add Option[T] support for primitives + string in case class macros

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1133]
In #1131 we could use null to represent None.

This is trickier for Options of case classes. On the Setter side, that is no problem. On the Converter side it is not clear what to do if you get some nulls and some non-nulls. You could:

1. If any of an Optional case class is null, the whole thing is null (might lead to silent data loss).
2. Throw an exception at runtime.

I can actually see the merit in going with 2. Cascading tuples are already not typesafe, and they can throw exceptions at runtime. So, allowing more expressivity which in the usual operation cannot fail might be a good idea.

**Comment by johnynek** [comment]
@ianoc this is closed now, right?

**Comment by ianoc** [comment]
Yep, i believe so.
