### ISSUE TITLE
FileSource could allow multiple localPaths

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1135]
for some terrible reason, in FileSource hdfsPaths is Iterable, but localPath is a string. Both can be used with MultiSourceTap, so there is really no reason for this asymmetry.

Also, several places in the code throw exceptions if there is not one path to pass to localPath, so that is pretty ugly.

**Comment by oeddyo** [comment]
Sorry for the mess. PR: https://github.com/twitter/scalding/pull/1275
