### ISSUE TITLE
Scalding gives StackOverflowError when line is too long

### ISSUE THREAD

**Issue by teresayanaxs** [twitter/scalding#1172]
I am trying to read from hdfs using scalding and it gives me an StackOverflowError exception when one of the columns in each row is too long.  (it works if the column is shortened, the column has 12000 characters long).  I am using scalding 0.12.0 and scala 2.10.4

Here's the snippet of the code

val axsUserSocialSchema = ('user_id, 'access_token, 'social_data, 'created_on, 'modified_on)
val axsUserSocialPipe = Csv(axsUserSocialHdfsPath, fields = axsUserSocialSchema, separator = "\001").read
val axsUserSocial = axsUserSocialPipe
                                 .write(Tsv("/user/data/tyan/data/out2"))

Error: cascading.flow.FlowException: internal error during mapper execution at cascading.flow.hadoop.FlowMapper.run(FlowMapper.java:148) at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:450) at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:415) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1614) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163) Caused by: java.lang.StackOverflowError at java.util.regex.Pattern$CharProperty$1.isSatisfiedBy(Pattern.java:3689) at java.util.regex.Pattern$CharProperty.match(Pattern.java:3694) at java.util.regex.Pattern$Curly.match0(Pattern.java:4148) at java.util.regex.Pattern$Curly.match(Pattern.java:4132) at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3715) at java.util.regex.Pattern$Curly.match0(Pattern.java:4177) at java.util.regex.Pattern$Curly.match(Pattern.java:4132) at java.util.regex.Pattern$GroupHead.match(Pattern.java:4556) at java.util.regex.Pattern$Loop.match(Pattern.java:4683) at java.util.regex.Pattern$GroupTail.match(Pattern.java:4615) at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3715) at java.util.regex.Pattern$Curly.match0(Pattern.java:4177) at java.util.regex.Pattern$Curly.match(Pattern.java:4132) at

**Comment by johnynek** [comment]
This looks like an issue with Java regexes, which the underlying cascading parser uses.

Parsing long lines with regexs can be a speed issue.

I'd suggest that you work around by using a TextLine source, and writing or using a more efficient method to split on commas. You might try this: http://commons.apache.org/proper/commons-csv/

**Comment by teresayanaxs** [comment]
Thanks very much for the tips.  I am able to use it with TextLine source without any StackOverFlow error

val axsUserSocial = axsUserSocialPipe.
                mapTo('line -> ('user_id,  'access_token,  'social_data, 'created_on, 'modified_on)) { line: String =>
                val Array(user_id, access_token, social_data, created_on, modified_on) = line.split("\001")
                (user_id, access_token,  social_data, created_on, modified_on)
           }
         .write(Tsv("/user/data/tyan/data/out2"))
