### ISSUE TITLE
Release scalding 0.13.0

### ISSUE THREAD

**Issue by isnotinvain** [twitter/scalding#1173]
Looks binary incompatible
```
[info] scalding-core: found 2 potential binary incompatibilities
[error]  * method apply(com.twitter.scalding.typed.TypedPipe,com.twitter.scalding.typed.TypedPipe,scala.math.Ordering,scala.math.Ordering)com.twitter.scalding.typed.TypedPipe in object com.twitter.scalding.typed.LookupJoin does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("com.twitter.scalding.typed.LookupJoin.apply")
[error]  * method withFilter(scala.Function1)com.twitter.scalding.typed.TypedPipe in trait com.twitter.scalding.typed.TypedPipe does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("com.twitter.scalding.typed.TypedPipe.withFilter")
[info] scalding-parquet: found 0 potential binary incompatibilities
[info] scalding-hadoop-test: previous-artifact not set, not analyzing binary compatibility
[info] scalding-hraven: found 0 potential binary incompatibilities
[info] scalding-jdbc: found 0 potential binary incompatibilities
[info] scalding-commons: found 0 potential binary incompatibilities
[info] scalding-repl: found 0 potential binary incompatibilities
[info] scalding-hadoop-test: found 0 potential binary incompatibilities
[info] scalding-avro: found 0 potential binary incompatibilities
[info] scalding-json: found 0 potential binary incompatibilities
[info] scalding-parquet-scrooge: found 0 potential binary incompatibilities
```

**Comment by johnynek** [comment]
We could easily fix those.

1) we could add back in an apply method that has the right parameters rather than using the default parameter support.

2) could be done via an enrichment. The implicit could be placed in TypedPipe object, and I think we get what we want (silence warnings about using TypedPipe in a for comprehension).

Those are easy fixes. Is it worth making it binary compatible?

That said, those are really small issues that I *seriously* doubt will burn anyone, and Algebird IS binary incompatible, so I think we should bump.

**Comment by ianoc** [comment]
Once Algebird is binary incompatible not sure how much it'll matter. And the second one is method addition, we probably don't mind that one. First one does seem very straight forward to work around though

**Comment by isnotinvain** [comment]
Do 1 and 2 sound good to have, or would they be adding cruft?

**Comment by johnynek** [comment]
since algebird is binary incompatible, let's skip it.

Probably virtually no one is going to get bit by the above issues anyway.

**Comment by isnotinvain** [comment]
OK, sounds good.
