### ISSUE TITLE
Travis builds don't say what scala version they are on

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1176]
This makes it a bit annoying to have to click and read the logs to see if 2.10 or 2.11 is giving up a problem.

**Comment by ianoc** [comment]
Where? its on the line for each test being run, far right column

**Comment by johnynek** [comment]
https://www.dropbox.com/s/g4s6qw1sst8wze4/Screenshot%202015-01-27%2011.15.02.png?dl=0

That's what I see and no way to scroll wider.

**Comment by ianoc** [comment]
Strange, do you have the rebuild button there?

mine looks more like 
![screen shot 2015-01-27 at 1 30 40 pm](https://cloud.githubusercontent.com/assets/446652/5927631/c6b65ba4-a628-11e4-9715-0a70d263c0af.png)

**Comment by johnynek** [comment]
Maybe you just need a really wide monitor, and not a 13 inch laptop monitor.

On Tue, Jan 27, 2015 at 11:31 AM, ianoc <notifications@github.com> wrote:

> Strange, do you have the rebuild button there?
>
> mine looks more like
> [image: screen shot 2015-01-27 at 1 30 40 pm]
> <https://cloud.githubusercontent.com/assets/446652/5927631/c6b65ba4-a628-11e4-9715-0a70d263c0af.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1176#issuecomment-71732029>.
>



-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by ianoc** [comment]
Yeah looks like their CSS is broken on the site, if you do command + - you can see it all

**Comment by caniszczyk** [comment]
You should be able to file an issue here: https://github.com/travis-ci/travis-web
