### ISSUE TITLE
A wiki for tutorials and usage tips of Execution

### ISSUE THREAD

**Issue by reconditesea** [twitter/scalding#1192]
Execution is still a relatively new feature and there are certain tips of how to use it correctly and efficiently. e.g. when to use .waitFor and when to use .run. Difference between .onComplete and .unit. 

There are comments in the code and scaladoc. But still we see many confusions both internal  and external. It would be really great if we can have a new wiki (or maybe update this one: https://github.com/twitter/scalding/wiki/Calling-Scalding-from-inside-your-application) with more tutorials and tips.

**Comment by jarutis** [comment]
That would be of great help indeed.

**Comment by johnynek** [comment]
So let's not overlook: http://twitter.github.io/scalding/#com.twitter.scalding.Execution

The docs there are pretty good, I think.

One problem we have is that everyone wants all the docs all the ways. Wiki's are not the greatest because you can't see all the wiki's that refer to code when you are editting that code, so it gets out of sync: it is not in CI, etc...

The scaladoc at least is right there with the code. I hope users will look at that and only use the wiki as a getting started example point.

Please feel free to edit the wiki and report back to this page. I'll add a couple of comments now.

**Comment by johnynek** [comment]
I updated the wiki with some comments.

**Comment by reconditesea** [comment]
@johnynek  Thanks, I think those comments are really helpful and answered many questions..
I still had only 1 confusion below:

"2. Avoid calling .waitFor or .run AS LONG AS POSSIBLE. Try to compose your entire job into on large Execution using .zip or .flatMap to combine Executions. waitFor is the same as run except it waits on the future."
Here we said avoid using .waitFor and .run. But in the examples above, we both use .waitFor to eventually kick off the jobs. I guess what is missing here is: we prefer using Execution composition to chain all different Executions. But on the end of the day, how should we start the final large Execution? Is it fair to say that there will be 1 (and should be only 1) calling to .waitFor or .run in each Execution App/Job?

**Comment by johnynek** [comment]
Yes. That is a good point: eventually you have to .run/.waitFor an
Execution, but the goal is, as you say, that EXACTLY one Execution do we
call .waitFor/.run. If you call .run on even two, you should try to instead
combine those two Executions with zip (to run in parallel) or flatMap (to
run them in a sequence).

On Tue, Feb 10, 2015 at 9:14 AM, Kevin Lin <notifications@github.com> wrote:

> @johnynek <https://github.com/johnynek> Thanks, I think those comments
> are really helpful and answered many questions..
> I still had only 1 confusion below:
>
> "2. Avoid calling .waitFor or .run AS LONG AS POSSIBLE. Try to compose
> your entire job into on large Execution using .zip or .flatMap to combine
> Executions. waitFor is the same as run except it waits on the future."
> Here we said avoid using .waitFor and .run. But in the examples above, we
> both use .waitFor to eventually kick off the jobs. I guess what is missing
> here is: we prefer using Execution composition to chain all different
> Executions. But on the end of the day, how should we start the final large
> Execution? Is it fair to say that there will be 1 (and should be only 1)
> calling to .waitFor or .run in each Execution App/Job?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1192#issuecomment-73762959>.
>



-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by reconditesea** [comment]
That makes great sense. I just added this sentence to the Wiki: There will be 1 (and should be only 1) calling to .waitFor or .run in each Execution App/Job.

Noted that there is no example code for Execution under tutorial folder yet. Will try to add some later.

**Comment by isnotinvain** [comment]
+1 for keeping the docs in the scaladocs

I think a compromise we can do is, in the wiki add a link to these scaladocs.
That way it's discoverable from the wiki but won't drift as the code evolves.

**Comment by reconditesea** [comment]
Closed by #1196
