### ISSUE TITLE
Disagreement between Docs and the Code for Column Projection w/ Parquet + Thrift

### ISSUE THREAD

**Issue by Gastove** [twitter/scalding#1201]
So. Not that there's a ton of docs, but what I can find is [here](https://github.com/Parquet/parquet-mr/blob/master/parquet_cascading.md). In it, we find: 

> Multiple glob expression can be joined together separated by ";". eg. "name;address/street"

However, if you actually do this, you get:

``` java
Caused by: java.lang.IllegalArgumentException: requirement failed: A column projection glob cannot contain a ; character
```

So. One or the other of these things is incorrect. Not perfectly sure which.

**Comment by isnotinvain** [comment]
Those are the docs for the parquet InputFormat, the docs for the scalding source (which wraps the input format) are here:
https://github.com/twitter/scalding/blob/develop/scalding-parquet/src/main/scala/com/twitter/scalding/parquet/thrift/ParquetThrift.scala#L87

Essentially, the source accepts a Set[String] and joins them on ";" for you

**Comment by isnotinvain** [comment]
If you think those docs could be more clear I'm happy to update the docs (or feel free to send a PR).
I'd also like to unify the filter + projection APIs -- one uses x/y/z paths and the other uses x.y.z which is unfortunate.

**Comment by Gastove** [comment]
Yeah, I'm struggling with getting this working at the moment; I'd be happy to send a PR, once I know what's going on. (In fairness, the issues I'm running in to could _easily_ be on my end, not scalding problems at all :P ) My inclination would be to PR against the markdown doc I linked above; is there a place you'd prefer this documentation live?

Clarifying question, while I've got your attention: projecting nested objects. Taking the `Address`/`Person` example from the doc I was looking at, if were using Scrooge/Scalding to read `Person` and wanted to project only the `Address`, the assumption is that I'd use `Set("person/address)`? 

(Also: does Scalding lower-case everything? A thrift struct named, say, `CustomerRecord` would have a column projection listing like `Set("customerrecord")`, yes?)

**Comment by isnotinvain** [comment]
The page you linked is on the parquet wiki, so we probably shouldn't put scalding specific stuff there.
But everything on that page applies to scalding, except for the part about ";" -- so the syntax / casing is exactly the same. I don't think anything gets lowercased, I think it has to match what's in your thrift IDL (it's based on the field names, not the field types).

I do see a typo in the parquet wiki though, it shouldn't say `address/{street,zip}` it should say `addr/{street,zip}` because `addr` is the name of the address field in the Person struct. If you want the entire Address object of the person struct, you would do: `Set("addr/**")` which says "give me every column in the addr field"

**Comment by Gastove** [comment]
Huh. Not `Set("addr/*")` (that is, single-aserisk) -- I thought double-asterisk was recursive?

**Comment by isnotinvain** [comment]
Just to clarify -- it has nothing to do with the name of the thrift struct, it's by the name of the *fields* in the struct.

Eg, if you have:
```
struct Address {
  1: string street
  2: string zip
}
struct Person {
  1: string name
  2: int16 age
  3: Address home
  4: Address alt
}
```

Then you could choose `Set("home/**")` or `Set("alt/**")` to get just one of the addresses, or `Set("home/**", "alt/**")` to get both addresses.

**Comment by Gastove** [comment]
Uh. Boy, does that not have the result I had expected. Which is to say: 

I have a file called `common.thrift` that defines types and structs we use all over the place. It looks a bit like this:

```
typedef string ID

enum IdType {
  APID = 1,
  UDID = 2
}

struct Identity {
  1: Id id
  2: IdType id_type
}
```

Then we have a record of an app open, so:
```
include "common.thrift"

struct Open {
  1: common.Identity identity
  2: common.ID app_id
}
```

If I try to read the `identity` using `Set("identity/**")`, I get:

```
Caused by: parquet.io.InvalidRecordException: required group identity = 1 {
  required binary id (UTF8) = 1;
  required binary id_type (ENUM) = 2;
  required int32 id_type = 2;
} found: expected optional group identity {
  optional binary id (UTF8);
  optional binary id_type (ENUM);
}
```

Any insight as to what on earth the `ENUM` is doing in the `required` statement? Any thoughts on what the heck is going on?
