### ISSUE TITLE
Typed JobTest with case class fails at runtime, while using a tuple works (field types problem)

### ISSUE THREAD

**Issue by turb** [twitter/scalding#1203]
This is an updated version of #760.

The updated test:

``` scala
package toto

import org.scalatest.{Matchers, FlatSpec}
import com.twitter.scalding.{Args, Job, JobTest, TDsl, TypedTsv}


case class Abc(a: Integer, b: Integer)

object Type {
  type T =
  Abc
  // (Integer, Integer)       // it works with this type!
}

class MinimalJob(args: Args) extends Job(args) {
  import TDsl._
  import Type._

  TypedTsv[T]("input", MinimalJob.fields)
    .flatMap { x:T => Seq(x, x) }
    .write(TypedTsv[T]("output", MinimalJob.fields))
}

object MinimalJob {
  val fields = new cascading.tuple.Fields(
    cascading.tuple.Fields.names(0, 1),
    cascading.tuple.Fields.types(classOf[Integer], classOf[Integer]))
}

class MinimalJobSpec extends FlatSpec with Matchers {
  import Type._

  "MinimalJob" should "work" in {
    JobTest(new MinimalJob(_))
      .source(TypedTsv[T]("input", MinimalJob.fields), Seq.empty[T])
      .sink[T](TypedTsv[T]("output", MinimalJob.fields)) { buff =>
      buff.length should be (0)
    }
      .run
      .finish
  }
}
```

The result is:

```
Failed to create a tap for: FixedPathTypedDelimited(List(input),0:1 | Integer, Integer,false,false, ,toto.Abc)
java.lang.RuntimeException: Failed to create a tap for: FixedPathTypedDelimited(List(input),0,false,false,  ,toto.Abc)
    at scala.sys.package$.error(package.scala:27)
    at com.twitter.scalding.FileSource$$anonfun$createTap$4.apply(FileSource.scala:166)
    at com.twitter.scalding.FileSource$$anonfun$createTap$4.apply(FileSource.scala:166)
    at scala.Option.getOrElse(Option.scala:120)
    at com.twitter.scalding.FileSource.createTap(FileSource.scala:166)
    at com.twitter.scalding.Source.read(Source.scala:99)
    at com.twitter.scalding.typed.TypedPipe$.from(TypedPipe.scala:42)
    at com.twitter.scalding.typed.TDsl$.mappableToTypedPipe(TDsl.scala:36)
    at toto.MinimalJob.<init>(TotoSpec.scala:19)
<snip>
```

The error is lost (grrr). The right one is:

```
java.lang.IllegalArgumentException: num of types must equal number of fields: [{2}:0:1 | Integer, Integer], found: 0
    at cascading.scheme.util.DelimitedParser.reset(DelimitedParser.java:176)
    at cascading.scheme.util.DelimitedParser.reset(DelimitedParser.java:126)
    at cascading.scheme.hadoop.TextDelimited.setSinkFields(TextDelimited.java:942)
    at cascading.scheme.hadoop.TextDelimited.<init>(TextDelimited.java:899)
<snip>
```

Is'nt that odd? I searched why, and I think I found the problem.

In Cascading, the corresponding code is the following:

``` java
<snip>
    if( types == null && sourceFields.hasTypes() )
      this.types = sourceFields.getTypes(); // gets a copy

<snip>

    if( this.types != null && this.types.length != sinkFields.size() )
      throw new IllegalArgumentException( "num of types must equal number of fields: " + sinkFields.printVerbose() + ", found: " + this.types.length );
<snip>
```

Why do not take the types I _explicitely_ gave him? Because `types` is not null. It is an empty array (length=0).

Why is it? We have to go back to Scalding code, in `TypeDelimited`:

``` scala
  override val types: Array[Class[_]] =
    if (classOf[scala.Product].isAssignableFrom(mf.erasure)) {
      //Assume this is a Tuple:
      mf.typeArguments.map { _.erasure }.toArray
    } else {
      //Assume there is only a single item
      Array(mf.erasure)
    }
```

Here, Scalding assumes it has a Tuple, so takes the type arguments. A case class is a tuple, yes (assignable from Product), but is has no type arguments, so the array is empty.

I think something should be done to help Cascading get a null (beh) and by so be able to set explicit field types.

**Comment by turb** [comment]
Note: of course the appropriate field name should be changed to match either tuple or case class. However, this failure comes next.

**Comment by ianoc** [comment]
Typed tsv does not support case classes I'm afraid. So I don't believe this
should work. There are other issues around recently on this

**Comment by turb** [comment]
@ianoc Thanks for the reply.

I am trying to test as proposed in http://www.agileatwork.com/unit-testing-scalding-jobs - but with case classes and types. Is there another source that I could use for that?

**Comment by ianoc** [comment]
Not heard of that site before, there are a lot of examples of using JobTest
in the tests here in the code, might be something in the wiki too.

**Comment by johnynek** [comment]
Case classes will be supported in the future, but we have to wire in the macros that we have for that rather than the runtime reflection based one used in TypedTsv.

To be clear: the only issue that is not supported now that you are hitting is that TypedTsv requires Tuples (or single primitive values).

**Comment by oscar-stripe** [comment]
By the way, this has been solved:

TypedText.tsv does support case classes:

https://github.com/twitter/scalding/blob/3e402e92640423e59b2b7baa501d30ec31746e4d/scalding-core/src/main/scala/com/twitter/scalding/source/TypedText.scala#L21
