### ISSUE TITLE
comb the code for deprecated things we can remove.

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1204]
This will be a judgement call, but let's try to get deprecated things out (especially if no one is using them at Twitter, which will be a good litmus test).

**Comment by oeddyo** [comment]
Need some pointers here :)

Is there any way to tell what is deprecated? 

I can see some "deprecate" warning while doing 
./sbt test

How do we know if someone is using them at Twitter (or anywhere else?)

**Comment by MansurAshraf** [comment]
Remove the deprecated methods and do a sandbox build would be the way to go

**Comment by oeddyo** [comment]
@MansurAshraf I'll take a look

**Comment by oeddyo** [comment]
Closing
