### ISSUE TITLE
Implement equals[T](a: TypedPipe[T], b: TypedPipe[T])

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1238]
You can create variants that return `Execution[Boolean]` and `ValuePipe[Boolean]`.

related to #520

**Comment by johnynek** [comment]
```scala
equals[T](a: TypedPipe[T], b: TypedPipe[T]): Execution[Boolean] = (a.asKeys.size).outerJoin(b.asKeys.size)
  .mapValues { case (left, right) => left == right }
  .values
  .groupAll
  .forall(identity)
  .values
  .toIterableExecution.map(_.headOption.getOrElse(false))
```
should be close

**Comment by isnotinvain** [comment]
This could include a way to compute the difference between two typed pipes as well.

**Comment by johnynek** [comment]
@isnotinvain can you think about releasing some of the code you wrote for this? Where should we put it?

**Comment by isnotinvain** [comment]
Yes, definitely. Well, I've said this before, but we don't have a great place for "recipes" or helper functions that don't belong in scalding-core, but use nothing but scalding. So, not sure, I guess somewhere in this repo :p

**Comment by isnotinvain** [comment]
https://github.com/twitter/scalding/pull/1266

Doesn't include equals, but equals is basically pipe1.diff(pipe2).isEmpty so we can add that on top if needed.
