### ISSUE TITLE
Remove use of String.split for simple cases in hot path.

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1249]
String.split uses a regex which is generally slow.

We should remove cases in the hot path with something like:

https://github.com/twitter/chill/blob/develop/chill-java/src/main/java/com/twitter/chill/config/ConfiguredInstantiator.java#L177

Particularly where we set the FlowProcess for Stats. That is calling .split now, and could be a perf issue. Also, caching, the same approach done in the chill code would be a huge win.

**Comment by oeddyo** [comment]
Seems like a doable task for me. I'm gonna take a look

**Comment by johnynek** [comment]
@oeddyo Great!

**Comment by oeddyo** [comment]
https://github.com/twitter/scalding/pull/1251
