### ISSUE TITLE
Is the source lookup in JobTest memoizing lookups correctly

### ISSUE THREAD

**Issue by Gabriel439** [twitter/scalding#1250]
I'm referring to this code (located [here](https://github.com/twitter/scalding/blob/c8313b402a23dbe3cdaa103baac6622c7a043309/scalding-core/src/main/scala/com/twitter/scalding/JobTest.scala#L85)):

```scala
  /** Add a function to produce a mock when a certain source is requested */
  def source[T](fn: Source => Option[Iterable[T]])(implicit setter: TupleSetter[T]): JobTest = {
    val oldSm = sourceMap
    val bufferTupFn = fn.andThen { optItT => optItT.map { _.map(t => setter(t)).toBuffer } }
    // We have to memoize to return the same buffer each time
    val memo = scala.collection.mutable.Map[Source, Option[Buffer[Tuple]]]()
    sourceMap = { (src: Source) => memo.getOrElseUpdate(src, bufferTupFn(src)).orElse(oldSm(src)) }
    this
  }
```

My understanding of this function is that this will create a fresh `memo` map every time you call it, and then the `getOrElseUpdate` method will always be a miss and not memoize anything.

However, I could be wrong because maybe Scala is weird and a mutable var defined within a method persists between multiple invocations of that same method?  Somebody more knowledgeable about Scala than me might be able to clarify what is going on.

I'm posting this issue on behalf of @oeddyo

**Comment by oeddyo** [comment]
Thanks for asking this for me :) @Gabriel439

**Comment by isnotinvain** [comment]
I'm not sure why it's this way, but it does appear to work as follows:

Each time `sourceMap` gets replaced with a new function, that delegates to the previous `sourceMap` function when there's a miss. The mutable map is being used basically as a mutable Tuple2 (holds 1 key and 1 value, which gets memoized).

So this boils down to essentially a List[Map[Source, Buffer]] and each time a lookup is done the list is scanned for maps containing the correct source buffer pair.

**Comment by isnotinvain** [comment]
cc @johnynek

**Comment by johnynek** [comment]
Yeah, it works basically like @isnotinvain said. It was added late and we wanted PartialFunctions to support more generality than just matching on Source.equals.

We had to pass a `(Source) => Iterable` at the end of the day to the Test mode, which handles mocking the sources.

It could be changed, but we need mutation because we don't want to call fn over and over again (on each lookup). You can change it if you want a different approach, but this does work.

**Comment by johnynek** [comment]
I'm closing this. Reopen if there is any indication of an error, but I think it is working.
