### ISSUE TITLE
skewJoinWithSmaller can drop entries

### ISSUE THREAD

**Issue by jnievelt** [twitter/scalding#1277]
In preparation of the replication step, skewJoinWithSmaller creates sampledCounts using an outer join:

https://github.com/twitter/scalding/blob/f999d89511b9d01850ab031d1e537de5491c94e2/scalding-core/src/main/scala/com/twitter/scalding/JoinAlgorithms.scala#L394

For entries that are sampled on only the left or right, this pipe will have entries that look something like:
> left_key: "foo"
> LEFT_SAMPLED_COUNT: 5
> right_key: null
> RIGHT_SAMPLED_COUNT: null

In skewReplicate, each side joins against their own key:

https://github.com/twitter/scalding/blob/f999d89511b9d01850ab031d1e537de5491c94e2/scalding-core/src/main/scala/com/twitter/scalding/JoinAlgorithms.scala#L455

On the left we'll match for left_key == "foo" which correctly finds the counts of (5, null).  On the right we'll match for right_key == "foo" which won't find anything (yielding (null, null), etc.).  As a result, the left & right pipe will replicate differently, leading to data loss.

Of course, it affects skewJoinWithLarger too.

**Comment by johnynek** [comment]
possibly related to #353 #349 #877
