### ISSUE TITLE
Improve TypedParquetTuple

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1302]
1) add macros to generate ParquetReadSupport and ParquetWriteSupport
2) We may need to change TypedParquetTupleScheme to accept instances rather than a class if reflecting a macro generated instance fails for some reason. If so, serialize and compress those instances (see Bijection's GzippedBase64String injection and JavaSerialization injection).
3) Make it a one-liner to read and write Parquet using case classes.

**Comment by JiJiTang** [comment]
Hi @johnynek , yes we can improve this. And I've just made a commit about this improvement in my forked repo and will create PR later.
