### ISSUE TITLE
tool.graph should call `validate` before `buildFlow`

### ISSUE THREAD

**Issue by rubanm** [twitter/scalding#1311]
If I'm reading it right, tool.graph should also call validate before buildFlow here:
https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/Tool.scala#L85

This will avoid skipping any actions done at the validate stage which some sources may require when buildFlow is subsequently called.

**Comment by ianoc** [comment]
That is odd then validate is required in every path to use a flow def. I
can see that potentially having odd bugs for people.

**Comment by rubanm** [comment]
Seems like this should hold at least for ToolRunner / Job classes?

In the regular case, ToolRunner calls validate + run (which includes buildFlow). Whereas, with tool.graph option it calls buildFlow only. Seems like it should be validate + buildFlow?

**Comment by ianoc** [comment]
The api doesn't require this, and we expose the flow def. So it would be an odd requirement that you must validate. Indeed a graph can still be produced if the data doesn't exist on disk. So i'm not sure the two should be correlated

**Comment by rubanm** [comment]
Ok that makes sense, thanks.
