### ISSUE TITLE
Parquet tuple macros have some hygiene bugs

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1319]
see: https://github.com/twitter/scalding/pull/1198/files#r32167540

**Comment by johnynek** [comment]
@JiJiTang would you have a chance to look at this?

**Comment by JiJiTang** [comment]
Hi @johnynek , this is fixed in this commit: https://github.com/JiJiTang/scalding/commit/60e7390ea018f291728aab65414e125108541e79 merged with PR #1303

**Comment by johnynek** [comment]
@JiJiTang sorry, indeed! I am using the previous version at Twitter (thanks again, BTW!) and I hit the issue. I can't wait to get the next release to make it even easier to use!
