### ISSUE TITLE
OrderedSerialization for com.twitter.util.Time does not exist

### ISSUE THREAD

**Issue by MansurAshraf** [twitter/scalding#1326]
It is fairly common for Jobs to groupBy on time

**Comment by johnynek** [comment]
that would make a dependency on twitter util, which is painful because they use the "overthewall" (or inside the monorepo) style to develop.

I doubt people outside Twitter are using util much with scalding, but I could be wrong.

Better, in my view, would be to make some combinators to transform OrderedSerializations when there are conversion functions (in this case, there is a mapping to Long).

**Comment by ianoc** [comment]
Yeah very twitter centric, and indeed very centric to the jobs your looking at Mansur. Wouldn't do anything in OSS around it. 

We could add some stuff to build bijected OrderedSerializations maybe?

def bijectedOrderedSerialization[T,U](implicit bij: Bijection[T, U], ordSer: OrderedSerialization[U])

**Comment by johnynek** [comment]
Yeah. I was thinking something like that (but maybe not depending on
bijection and just taking two functions, to keep zero dependencies in
scalding-serialization).

On Wed, Jun 17, 2015 at 10:19 AM, ianoc <notifications@github.com> wrote:

> Yeah very twitter centric, and indeed very centric to the jobs your
> looking at Mansur. Wouldn't do anything in OSS around it.
>
> We could add some stuff to build bijected OrderedSerializations maybe?
>
> def bijectedOrderedSerializationT,U
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1326#issuecomment-112936330>.
>



-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by ianoc** [comment]
Yeah that seems like a good thing to do we could provide the bijection interface in scalding-core then if we want to have it too

**Comment by johnynek** [comment]
yep. That sounds good.

On Wed, Jun 17, 2015 at 10:24 AM, ianoc <notifications@github.com> wrote:

> Yeah that seems like a good thing to do we could provide the bijection
> interface in scalding-core then if we want to have it too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1326#issuecomment-112939168>.
>



-- 
Oscar Boykin :: @posco :: http://twitter.com/posco
