### ISSUE TITLE
Improve wiki/documentation for new users

### ISSUE THREAD

**Issue by sid-kap** [twitter/scalding#1354]
I believe there's room for improvement for the wiki/documentation to make it easier for new Scalding users to get started.

Here are some potential problems I see with the wiki:
- The documentation isn't linear. There is no obvious order in which new users should read the documentation.
- It's not clear how important each item in the documentation is, or who should read it.
- The Alice in Wonderland walkthrough is just a Gist, with little text. We should make this into a markdown walkthrough which displays the output of each step, so that the readers don't have to run it on their own machine.

Here are some ideas I have on how to improve the documentation:
- Move to Github Pages (with Jekyll or a similar static-site generator), so that we can make the docs prettier and have better structure. Jekyll should allow us to have a hierarchy, something like:
```
- What is Scalding?
- Tutorial
    - Beginner
        - Getting Started (installing, opening the REPL, etc.)
        - Pipes, Typed Pipes, and Sources
        - Basic aggregations (Alice in Wonderland)
    - Intermediate
        - Running in Hadoop mode
        - Advanced aggregations
        - Using Algebird aggregators
    - Advanced
        - Building bigger platforms with Scalding
        - Getting started with the Matrix API
- Reference/Other
    - Troubleshooting
    - Rosetta Code (SQL, Pig, Hive, etc.)
    - Matrix API
    - Upgrading to 0.9.0
    - Third-Party Modules
    - Videos
        - Oscar's Scalding Talk
        - other videos
```
Moving to Github Pages will also allow us to use Travis CI and Tut-based documentation.

**Comment by johnynek** [comment]
sounds good to me. Care to get us started?

In the mean time, editing the wiki to be more in line with this would be a fine start, if you ask me.

**Comment by sid-kap** [comment]
Sounds good. :+1: 
I'll take a stab at it on my fork, and I'll keep you updated.

**Comment by sid-kap** [comment]
I decided to go with ReadTheDocs instead of Github Pages. Here's a first draft:

http://scalding.readthedocs.org/en/readthedocs/gen/

ReadTheDocs is awesome!
I've set it up to track my branch, sid-kap/scalding/readthedocs, and re-generate the site every time I push. Every time I push, it compiles scalding and then runs every .md file in the docs/src directory through tut. It then uses sphinx to generate the static site.

RTD allows you to generate docs for multiple branches. So, for example, we could turn on doc generation for both the master and develop branches. You can also have it generate pages for an issue branch, so if someone makes a pull request to update the docs, you can preview that branch's output before merging it in.

**Comment by johnynek** [comment]
This looks really cool to me, but could we get this into the main repo setup and deprecate/put a link from the wiki?

We might also use:
https://github.com/tpolecat/tut

to compile our test code inside the markdown.

**Comment by sid-kap** [comment]
This setup is actually using tut right now. 
Anything in the docs/src directory goes through tut before being converted to HTML. (This happens on the readthedocs server every time I push to my branch.)

To bring this into the main repo, we would need to:
* merge in the sid-kap/readthedocs branch into develop
* go to readthedocs.com and turn on documentation for the develop branch (For some reason RTD gave me the permissions to control all of scalding readthedocs, even for branches that don't belong to me. I can assign permissions to more people though.) 

I should probably clean up the docs more before we think about merging it in, though.
