### ISSUE TITLE
ReduceOperations for Typed API?

### ISSUE THREAD

**Issue by sid-kap** [twitter/scalding#1374]
The ReduceOperations trait contains functions like approximateUniqueCount, hyperLogLog, and sizeAveStdev that make it easy for people (using the Fields API) to use Algebird aggregators on their RichPipes.

Would it be a good idea to have something like this for the Typed API? 
People might be more inclined to use Algebird structures if it was as simple as changing, for example, `keyedListLike.toSet.mapValues(_.size)` to `keyedListLike.approximateUniqueCount`, rather than going into the documentation and figuring out how to instantiate an instance of the HyperLogLogAggregator.

**Comment by johnynek** [comment]
Our general approach with the typed-API is to recommend using Aggregators:

https://github.com/twitter/scalding/wiki/Aggregation-using-Algebird-Aggregators

For instance:

https://github.com/twitter/algebird/blob/develop/algebird-core/src/main/scala/com/twitter/algebird/Aggregator.scala#L131

```
myPipe.aggregate(Aggregator.approximateUniqueCount)
// or
myPipe.groupBy(someFn)
  .aggregate(Aggregator.approximateUniqueCount)
```

**Comment by sid-kap** [comment]
That's exactly what I was looking for!
Thanks.
