### ISSUE TITLE
Hadoop Configuration asScala conversion might be broken

### ISSUE THREAD

**Issue by rubanm** [twitter/scalding#1398]
Ran into this during https://github.com/twitter/scalding/pull/1397

In the repl:
```scala
scalding> val Hdfs(_, conf) = implicitly[Mode]

scalding> conf.get("mapred.reduce.tasks")
res0: String = 1

scalding> com.twitter.scalding.Config.fromHadoop(conf).get("mapred.reduce.tasks")
res1: Option[String] = None
```
On checking further:
```scala
scalding> import scala.collection.JavaConverters._
import scala.collection.JavaConverters._

scalding> conf.asScala.filter(_.getKey == "mapred.reduce.tasks")
res3: Iterable[java.util.Map.Entry[String,String]] = List()

scalding> val it = conf.iterator

scalding> while(it.hasNext) { val a = it.next; if (a.getKey ==  "mapred.reduce.tasks") println(a) }
// Nothing is printed
```

This does not repro for some of the other keys I tried with, but it does look like something is broken in the iterator.

The iterator codepath is used for creating com.twitter.scalding.Config objects so this needs to be investigated I think.

**Comment by ianoc** [comment]
The Hadoop config isn't a real map... Or well it is but lots of logic in
front. You need to set those reducers to some magical number like 3495 then
iterate through and look for a value that looks like it. I suspect that
might work ?

**Comment by johnynek** [comment]
I think what may be going on here is the Hadoop key mapping business
between Hadoop 1 and 2. It might not apply when we use the iterator (I
guess it doesn't).

On Saturday, August 1, 2015, ianoc <notifications@github.com> wrote:

> The Hadoop config isn't a real map... Or well it is but lots of logic in
> front. You need to set those reducers to some magical number like 3495 then
> iterate through and look for a value that looks like it. I suspect that
> might work ?
>
> On Saturday, August 1, 2015, Ruban Monu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Ran into this during #1397 <
> https://github.com/twitter/scalding/pull/1397>
> >
> > In the repl:
> >
> > scalding> val Hdfs(_, conf) = implicitly[Mode]
> >
> > scalding> conf.get("mapred.reduce.tasks")
> > res0: String = 1
> >
> > scalding>
> com.twitter.scalding.Config.fromHadoop(conf).get("mapred.reduce.tasks")
> > res1: Option[String] = None
> >
> > On checking further:
> >
> > scalding> import scala.collection.JavaConverters._import
> scala.collection.JavaConverters._
> >
> > scalding> conf.asScala.filter(_.getKey == "mapred.reduce.tasks")
> > res3: Iterable[java.util.Map.Entry[String,String]] = List()
> >
> > scalding> val it = conf.iterator
> >
> > scalding> while(it.hasNext) { val a = it.next; if (a.getKey ==
> "mapred.reduce.tasks") println(a) }// Nothing is printed
> >
> > This does not repro for some of the other keys I tried with, but it does
> > look like something is broken in the iterator.
> >
> > The iterator codepath is used for creating com.twitter.scalding.Config
> > objects so this needs to be investigated I think.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/twitter/scalding/issues/1398>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1398#issuecomment-126993212>.
>


-- 
Oscar Boykin :: @posco :: http://twitter.com/posco
