### ISSUE TITLE
JobTest#run hangs if Stat is used

### ISSUE THREAD

**Issue by nevillelyh** [twitter/scalding#1408]
StatsTest hangs in the following example. It works when using `runHadoop`.

```scala
package com.twitter.scalding

import org.scalatest.{ Matchers, WordSpec }

class StatsTestJob(args: Args) extends Job(args) {
  val records = Stat("number of records", "stats")
  val nonZero = Stat("number of non-zero records", "stats")

  TypedPipe.from(TypedTsv[(String, Int)](args("input")))
    .map { kv =>
      if (kv._2 != 0) nonZero.inc
      records.inc
      kv
    }
    .write(TypedTsv[(String, Int)](args("output")))
}

class StatsTest extends WordSpec with Matchers {

  "StatsTestJob" should {
    "pass" in {
      val testInput = List(("a", 0), ("b", 1), ("c", 2))

      JobTest(new StatsTestJob(_))
        .arg("input", "input")
        .arg("output", "output")
        .source(TypedTsv[(String, Int)]("input"), testInput)
        .sink[(String, Int)](TypedTsv[(String, Int)]("output")){ outBuf => outBuf shouldBe testInput }
        .run
    }
  }

}

```

**Comment by ianoc** [comment]
Please open a PR with a failing test, should be able to add it beside the other counter tests.

**Comment by johnynek** [comment]
Can you try .runHadoop instead of .run as a work around? There seems like
there are issues with counters in local mode. :(

On Wednesday, August 5, 2015, ianoc <notifications@github.com> wrote:

> Please open a PR with a failing test, should be able to add it beside the
> other counter tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1408#issuecomment-128091291>.
>


-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by nevillelyh** [comment]
Scratch that. The hanging was caused by some other change I have.
