### ISSUE TITLE
Release 0.16.0

### ISSUE THREAD

**Issue by ianoc** [twitter/scalding#1413]
What do we have not in, what do we want done to cut the next release for OSS?

We have a pretty large backlog of things all done since the last release : 
-> Hyperdoop increased stability, ready for GA in its own serialization module
-> Collapsed the macro packages into their parents to improve dependency mgmt
-> Scalding macro based jdbc (this might not be merged?)
-> TypedText
-> Line numbers in a lot of descriptions
-> Parquet typed tuple improvements

* Make sure Execution.zip fails fast: https://github.com/twitter/scalding/pull/1412
* add counter verification logic: https://github.com/twitter/scalding/pull/1409
* Add some return types: https://github.com/twitter/scalding/pull/1407
* add .groupWith method to TypedPipe: https://github.com/twitter/scalding/pull/1406
* Adds a function to test if a sink exists at the version we created: https://github.com/twitter/scalding/pull/1404
* Add the type in ScroogeReadSupport: https://github.com/twitter/scalding/pull/1403
* Change hash function in GroupRandomly: https://github.com/twitter/scalding/pull/1401
* Improve logging in runtime reducer estimators: https://github.com/twitter/scalding/pull/1402
* Fixes the scrooge generator tasks not to generate code in the compile…: https://github.com/twitter/scalding/pull/1399
* Ianoc/configure set converter: https://github.com/twitter/scalding/pull/1400
* RatioBasedEstimator - fix threshold edge case, add tests: https://github.com/twitter/scalding/pull/1397
* Inline parquet-scrooge: https://github.com/twitter/scalding/pull/1395
* Support nesting Options in TypeDescriptor: https://github.com/twitter/scalding/pull/1387
* Remove use of hadoop version in estimators: https://github.com/twitter/scalding/pull/1391
* Handle no history case in RatioBasedEstimator: https://github.com/twitter/scalding/pull/1393
* Upgrade parquet to 1.8.1: https://github.com/twitter/scalding/pull/1380
* Set hadoop version to dummy value: https://github.com/twitter/scalding/pull/1392
* Enable Scalding-REPL for Scala 2.11: https://github.com/twitter/scalding/pull/1388
* Updates for some upstream fixes/changes: https://github.com/twitter/scalding/pull/1390
* Ordered Serialization macros for thrift: https://github.com/twitter/scalding/pull/1338
* Don&#39;t publish maple when doing 2.11 so we only publish it once -- nee…: https://github.com/twitter/scalding/pull/1386
* Just move whitespace, add comments, simplify a few methods: https://github.com/twitter/scalding/pull/1383
* Upgrade sbt launcher script (sbt-extras): https://github.com/twitter/scalding/pull/1381
* Add monoid and semigroup for Execution: https://github.com/twitter/scalding/pull/1379
* Add NullSink and test: https://github.com/twitter/scalding/pull/1378
* Runtime reducer estimator: https://github.com/twitter/scalding/pull/1358
* A serialization error we were seeing in repl usage: https://github.com/twitter/scalding/pull/1376
* Fix deprecation warnings in TypedDelimited: https://github.com/twitter/scalding/pull/1371
* Revert typed tsv behavior: https://github.com/twitter/scalding/pull/1373
* Fix TypedPipe.limit to be correct, if slighly slower: https://github.com/twitter/scalding/pull/1366
* Ianoc/revert changes around making file systems: https://github.com/twitter/scalding/pull/1372
* Fix scala.Function2 showing up in line numbers: https://github.com/twitter/scalding/pull/1367
* Drop with MacroGenerated from Fields macros: https://github.com/twitter/scalding/pull/1370
* Migrate typedtext: https://github.com/twitter/scalding/pull/1356
* Missing an extends Serializable, causes issues if capture Config&#39;s an…: https://github.com/twitter/scalding/pull/1365
* Allow overriding of hadoop configuration options for a single source/…: https://github.com/twitter/scalding/pull/1362
* Update Build.scala: https://github.com/twitter/scalding/pull/1361
* Merge scalding-macros into scalding-core: https://github.com/twitter/scalding/pull/1355
* Adding a source for the most recent good date path.: https://github.com/twitter/scalding/pull/20
* Consistent style in homepage example: https://github.com/twitter/scalding/pull/1349
* Serialization folding: https://github.com/twitter/scalding/pull/1351
* Collapses scalding-db packages: https://github.com/twitter/scalding/pull/1353
* Adds jdbc macros from internal: https://github.com/twitter/scalding/pull/1267
* make some repl components extensible: https://github.com/twitter/scalding/pull/1342
* Implement flatMapValues method: https://github.com/twitter/scalding/pull/1348
* Fix the execution test: https://github.com/twitter/scalding/pull/1347
* Remove the bootstrap section: https://github.com/twitter/scalding/pull/1346
* Execution id code: https://github.com/twitter/scalding/pull/1334
* Add line numbers at .group and .toPipe boundaries: https://github.com/twitter/scalding/pull/1335
* Change defaults for Scalding reducer estimator: https://github.com/twitter/scalding/pull/1333
* faster builds on travis by a bit.: https://github.com/twitter/scalding/pull/1280
* Change groupRandomly &amp; groupAll to use OrderedSerialization: https://github.com/twitter/scalding/pull/1307
* Make SketchJoin ordered serialization aware: https://github.com/twitter/scalding/pull/1316
* Add secondary sorting using ordered serialization: https://github.com/twitter/scalding/pull/1321
* Hide the deprecated string error for getting ASCII bytes.: https://github.com/twitter/scalding/pull/1332
* Add a OrderedSerialization.viaTransform with no dependencies, and a B…: https://github.com/twitter/scalding/pull/1329
* Precompute int hashes: https://github.com/twitter/scalding/pull/1330
* Added a sealed trait ordered serializer. When it works its great. Not…: https://github.com/twitter/scalding/pull/1320
* Apply merge strategy for pom.xml files: https://github.com/twitter/scalding/pull/1327
* Bails out from the length calculation if we don&#39;t succeed often, leng…: https://github.com/twitter/scalding/pull/1322
* Apply merge strategy for pom.properties files: https://github.com/twitter/scalding/pull/1325
* Add `withDescription` for naming MR steps: https://github.com/twitter/scalding/pull/1283
* increased number of box instances to 250: https://github.com/twitter/scalding/pull/1323
* Fix testing VersionedKeyValSource#toIterator for non-Array[Byte] types: https://github.com/twitter/scalding/pull/1314
* make LongThrift sources TypedSink: https://github.com/twitter/scalding/pull/1313
* Make test of Kmeans very very unlikely to fail: https://github.com/twitter/scalding/pull/1310
* Revert &quot;Add UnitOrderedSerialization&quot;: https://github.com/twitter/scalding/pull/1306
* Add UnitOrderedSerialization: https://github.com/twitter/scalding/pull/1304
* Improve TypedParquetTuple #1302: https://github.com/twitter/scalding/pull/1303
* Add tests around hashcode collisions: https://github.com/twitter/scalding/pull/1299
* make serialization modules build on travis: https://github.com/twitter/scalding/pull/1301
* Fix performance bug in TypedPipeDiff: https://github.com/twitter/scalding/pull/1300

**Comment by ianoc** [comment]
@rubanm , @johnynek ^^

**Comment by johnynek** [comment]
something is goofy with that list. It is including some very old pull requests (like #15)

**Comment by rubanm** [comment]
Looks like those are PR numbers from my fork that got mixed in here :-/

I think @sid-kap's updated runtime-based reducer estimator is almost ready https://github.com/twitter/scalding/pull/1411 so can be added here.

The jdbc one might not make it. I think it needs some more work.

**Comment by johnynek** [comment]
This looks pretty good to me. I'd rather either 1) organize the JDBC stuff a bit better or 2) not merge for this release, and push till next time. Just my opinion there.

Also, we should work on some release notes (maybe in a google doc) to get the high level things here.

Some things that pop to mind: separate new features, enhancements and bugfixes.

New Features:
OrderedSerialization deemed production ready (explain what it offers, describe how to use it, mention 30-50% perf wins we see).
TypedText: typesafe flattening of case-classes, tuples and primitives into TSV and CSV formats
Line numbers in config (for map/reduce boundaries, not all methods)
withDescription for naming steps

Enhancements:
Executions are monoids and semigroups.
Failed Executions combined with zip fail faster (`a.zip(b)` is failed as soon as either `a, b` fails). 
LongThrift sources in scalding-commons are TypedSinks
Scalding REPL supported for 2.11
added TypedPipe.groupWith for a cleaner way to be explicit about the ordering to use.

Bugfix:
VersionedKeyValSource#toIterator fixed for types other than `Array[Byte]`
TypedPipe.limit (now is an exact computation while before .limit(n) returned AT MOST n items but could return 0 when there were more than 0 items. The fix means it could be slightly slower but fixes issues we've seen with people misusing the API).

Also, I guess we should link to the relevant PRs in the above (the OrderedSerialization may have a ton, maybe that's a bad idea for that one).

Are these the main issues?

**Comment by sriramkrishnan** [comment]
FYI 0.16.0 RC - https://github.com/twitter/scalding/releases/tag/v0.16.0-RC6

CC @piyushnarang

**Comment by johnynek** [comment]
We need release notes... Maybe a PR so we can use github to suggest edits?

**Comment by piyushnarang** [comment]
Closing this as the 0.16.0 release is now out.
