### ISSUE TITLE
Matrix2 does not support OrderedSerialization.

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1418]
Ofter `Ordering`s are composed in here:

https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/mathematics/Matrix2.scala

We need to do that using:
https://github.com/twitter/scalding/blob/develop/scalding-serialization/src/main/scala/com/twitter/scalding/serialization/Serialization2.scala#L61

if all Orderings are OrderedSerializations. We probably need some method like:

```scala
implicit def withOrderedSerialization[A: Ordering, B: Ordering]: Ordering[(A, B)] =
  // if both Orderings are OrderedSerialization, use OrderedSerialization2, else Ordering.tuple2 
```
and use that in internal methods.

**Comment by reconditesea** [comment]
@johnynek Here I think if the individual ordering for row/col is an OrderedSerialization, it will just work. But for the composed ordering of the two, we will need to add OrderedSerialization support. Is this correct?

**Comment by johnynek** [comment]
Yes, that's right. Sometimes we group on the pair, and that needs to be composed properly.
