### ISSUE TITLE
Specialize return types of `TypedText.{tsv,csv,osv}`

### ISSUE THREAD

**Issue by Gabriel439** [twitter/scalding#1429]
Currently the `TypedText` object provides the following helper functions:

```scala
def tsv[T: TypeDescriptor](path: String*): TypedTextDelimited[T] = new FixedTypedText[T](TAB, path: _*)
def osv[T: TypeDescriptor](path: String*): TypedTextDelimited[T] = new FixedTypedText[T](ONE, path: _*)
def csv[T: TypeDescriptor](path: String*): TypedTextDelimited[T] = new FixedTypedText[T](COMMA, path: _*)
```

The type annotation on the return values (`TypedTextDelimited`) is more general than the right-hand side (`FixedTypedText`), which means that they will fail for any function expecting a `FileSource` super-class, such as `TypedPipe.make`:

```scala
scala> execute(someTypedPipe.make[Int](TypedText.tsv[Int]("temp.tsv")))
<console>:27: error: type mismatch;
 found   : com.twitter.scalding.source.TypedTextDelimited[Int]
 required: com.twitter.scalding.FileSource with com.twitter.scalding.typed.TypedSink[Int] with com.twitter.scalding.typed.TypedSource[Int]
                                      execute(someTypedPipe.make[Int](TypedText.tsv[Int]("temp.tsv")))
```

... and they would succeed if they had the more specific `FixedTypedText` annotation instead of `TypedTextDelimited` because `FixedTypedText` extends `FileSource` whereas `TypedTextDelimited` does not.

Is there any reason for the `TypedTextDelimited` annotations, or could they be changed to `FixedTypedText`?

**Comment by johnynek** [comment]
No good reason. Mostly to keep less specific types which generally cause less migration pains.

It might be good to have a type that is `FileSource with TypedSource[T] with TypedSink[T]` and often that might be what we want, but in this case, maybe we just want to return FixedTypedText.

**Comment by joshualande** [comment]
@Gabriel439 thanks for opening this ticket! =)

**Comment by nathantchan** [comment]
This became an issue for me in some recent adhoc analysis.
```
<console>:67: error: type mismatch;
 found   : com.twitter.scalding.source.TypedTextDelimited[T]
 required: com.twitter.scalding.FileSource with com.twitter.scalding.typed.TypedSink[T] with com.twitter.scalding.typed.TypedSource[T]
                        .make(LzoTypedText.dailyLzoOsv[T]("file"))
                                                                         ^
```

**Comment by joshualande** [comment]
Thanks so much!!! ^_^
