### ISSUE TITLE
`readPathsFor` ignores `tz` argument

### ISSUE THREAD

**Issue by Gabriel439** [twitter/scalding#1438]
[The default `readPathsFor` implementation](https://github.com/twitter/scalding/blob/cf7ae11432b5e4037f7a632cfda2ae2e4f39636a/scalding-core/src/main/scala/com/twitter/scalding/TimePathedSource.scala#L48) in `TimePathedSource.scala` ignores its `tz` argument:

```scala
  /**
   * Gives all read paths in the given daterange.
   */
  def readPathsFor(pattern: String, dateRange: DateRange, tz: TimeZone): Iterable[String] = {
    TimePathedSource.stepSize(pattern, DateOps.UTC) match {
      case Some(duration) => allPathsWithDuration(pattern, duration, dateRange, DateOps.UTC)
      case None => sys.error(s"No suitable step size for pattern: $pattern")
    }
  }
```

Instead, it explicitly passes `DateOps.UTC` to `TimePathedSource.stepSize`.  Is there any particular reason why it doesn't pass through `tz` instead of hard-coding `DateOps.UTC`?

**Comment by ianoc** [comment]
Can't imagine why, just a bug i'd imagine

**Comment by rubanm** [comment]
Closed by https://github.com/twitter/scalding/pull/1439
