### ISSUE TITLE
Documentation question about mapValues in type-safe API

### ISSUE THREAD

**Issue by praveen-srinivasan** [twitter/scalding#1447]
Hi,
In 
https://github.com/twitter/scalding/wiki/Type-safe-api-reference

there is a line: 

group.mapValues { values => mappingFunction(values) } 

This looks like mappingFunction is supposed to operate on multiple values at once, but if I understand correctly, mappingFunction actually operates on a single value at a time. Could this be changed to: value => mappingFunction(value) ?

**Comment by benpence** [comment]
Yes, great point. Updated!
