### ISSUE TITLE
Documentation of sample in TypedPipe

### ISSUE THREAD

**Issue by praveen-srinivasan** [twitter/scalding#1448]
The sample method of TypedPipe is documented as taking "percent" as an argument. But percent is typically in [0,100], while if I understand the code correctly, the argument is really supposed to be a fraction, or a value in [0,1.0] . Are people open to changing the documentation for this?

**Comment by johnynek** [comment]
yes. Very open to that. Pull requests to improve the documentation are greatly appreciated.
