### ISSUE TITLE
Add separate InvalidSourceTap for dealing with no valid paths in FileSource

### ISSUE THREAD

**Issue by rubanm** [twitter/scalding#1454]
The following can lead to edge cases:
https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/FileSource.scala#L264

The assumption is that validateTaps throws if validation fails, but there are codepaths like source.toIterator where validate is not called.

Adding separate InvalidSourceTap that throws in openForRead can cover both the regular read and toIterator cases I think.

**Comment by johnynek** [comment]
This sounds reasonable. It is definitely bad that we have two code paths.

**Comment by reconditesea** [comment]
@rubanm, @johnynek I had a first crack on this: https://github.com/twitter/scalding/pull/1458
