### ISSUE TITLE
FileSystem.get(conf) is not safe

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1486]
This always gets the default FS and precludes using something like s3. See:

https://forums.aws.amazon.com/thread.jspa?threadID=30945

The correct pattern appears to be `FileSystem.get(uri, conf)` where `uri` points to the FileSystem in question.

This happens three times in this file:
https://github.com/twitter/scalding/blob/develop/scalding-commons/src/main/java/com/twitter/scalding/commons/tap/VersionedTap.java#L154

**Comment by isnotinvain** [comment]
I think also, new Path(uri).getFileSystem(conf) works?

**Comment by johnynek** [comment]
yes, I agree.
