### ISSUE TITLE
RatioBasedEstimator should use MAP_OUTPUT_BYTES 

### ISSUE THREAD

**Issue by gerashegalov** [twitter/scalding#1510]
https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/reducer_estimation/RatioBasedEstimator.scala#L64

uses FILE_BYTES_READ which has the following issues:
- it's a post-compression counter while the reducer has to decompress in order to sort
- it includes unrelated reads from DistributedCache and other side files.
- less significant since rare, does not deal correctly with in-memory shuffle and merge.

I suggest to use the pre-compression MAP_OUTPUT_BYTES counter instead.

**Comment by gerashegalov** [comment]
This may require a change in hraven. 

Alternatively We may use reduceShuffleBytes to get rid of unrelated local filesystem reads. But we would need to check the map output compression codec and have some heuristic compression values it translates to.

**Comment by vrushalivc** [comment]
Thanks @gerashegalov ! wanted to know what change do you foresee in hRaven, perhaps it is feasible? hRaven respose will have all the counters (whatever params are asked for)

**Comment by gerashegalov** [comment]
@vrushalic MAP_OUTPUT_BYTES is a task-level MR counter. Can we have an O(1) space and runtime mapOutputBytes rolled up for a job.
