### ISSUE TITLE
should register all boxed classes

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1524]
https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/serialization/KryoHadoop.scala#L57

if we don't register, they are not assigned tokens, which slows serialization down.

**Comment by isnotinvain** [comment]
that comment makes it look like they aren't supposed to be registered?

**Comment by johnynek** [comment]
well, the point is that registered kryo classes get cascading tokens:

https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/Config.scala#L191

which is the real issue. By registering them with Kryo we avoid having two paths to get cascading tokens set.
