### ISSUE TITLE
Rounding Bug in RatioBasedEstimator

### ISSUE THREAD

**Issue by isnotinvain** [twitter/scalding#1541]
Currently the formula we use is:

```
val baseEstimate: Int = delegateToInputSizeEstimator(...)
val e = (baseEstimate * reducerRatio).ceil.toInt max 1
```

However, if the baseEstimate was initially tiny (say we need about 0.01 reducers) and then that gets rounded up to 1, and now our reducerRatio is rather large, when multiplied together we get something large. Instead of `.01 * reducerRatio` we have `ceil(.01) * reducerRatio`

So I think the fix is here:
https://github.com/twitter/scalding/blob/bb1c4d2d454eec85d65dd4d27d5399e17cb7c619/scalding-core/src/main/scala/com/twitter/scalding/reducer_estimation/RatioBasedEstimator.scala#L72

We need to add a static helper method to InputSizeReducerEstimator that returns a Double instead of an Int and call that instead of using the already `ceil`ed estimate.

**Comment by johnynek** [comment]
So the issue is that `Int` does not compose well due to this `ceil` effect. I guess using `Double` is a fine way to signal when you need much less that 1 reducer.

Seems fine to me, but is obviously binary incompatible.

**Comment by isnotinvain** [comment]
I don't think it's binary incompatible. Fixing the trat to use Doubles would be. But we can give InputSizeReducerEstimator a method that returns double in addition to the one that returns int w/o breaking compatibility. PR on the way

**Comment by gerashegalov** [comment]
@isnotinvain Are you also adding some reasonable cap? I would make it configurable with a default 5000.

**Comment by isnotinvain** [comment]
Yeah we could add a cap too.
This isn't done, but just to illustrate:
https://github.com/twitter/scalding/pull/1542
