### ISSUE TITLE
forceToDiskExecution does not clean up data after the execution has completed

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1615]
We assume that people have tmpdir cleaning set up, but not everyone does.

It would be nice to delete any files created with forceToDiskExecution after the executions have totally completed (when the EvalCache is stopped):

https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/Execution.scala#L151

**Comment by ulyssepence** [comment]
What is "tmpdir cleaning"? Is it a Hadoop service or configuration property? Could we just enable it? Are we already deleting files in Scalding?

**Comment by isnotinvain** [comment]
If we write this data to the same place that is used for "MR temp" by hadoop, it should probably be left to the cluster to decide how those deletes are handled? But maybe there is no such thing in some contexts (like s3?)

**Comment by johnynek** [comment]
cascading cleans up after itself, but we don't really have to except in this case.

tmpdir cleaning just means that at Twitter you have some cron process that deletes old files from tmp. Not everyone does that. Tmp is just there, always growing when forceToDiskExecution is being used.

**Comment by johnynek** [comment]
I think private temporary data should be removed when we complete. I see no reason we want to litter the tmp directory at all.

**Comment by ulyssepence** [comment]
OK got it
