### ISSUE TITLE
Port our macros to using macro-compat

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1619]
https://github.com/milessabin/macro-compat

Miles has a good track record of compatibility. Using this package would allow us to get rid of our warnings that we have for 2.10.

cc @ianoc

**Comment by ianoc** [comment]
Seems like a good step, until/unless we need it for 2.12 I don't think it'll rise up for something i'd have cycles for. But would be very bullish on someone taking this on if they have time

**Comment by johnynek** [comment]
seems like we should drop this since we dropped 2.10 support.
