### ISSUE TITLE
Execution support for keepAlive

### ISSUE THREAD

**Issue by ulyssepence** [twitter/scalding#1638]
By default, I believe we are queueing up a heartbeat to Hadoop after processing each tuple from cascading. The `Job` class exposes `#keepAlive()` (https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/Job.scala#L80) to enable users that perform large operations on each tuple to send their own heartbeat to prevent the containing Hadoop node from being killed.

We do not expose anything like `#keepAlive()` in `Execution`, which should have feature parity with `Job`. While using `keepAlive()` is not necessarily idiomatic to `Execution`, I don't think it's necessarily wrong to use this feature in workflows.

**Comment by johnynek** [comment]
we do have this:
`https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/Stats.scala#L142`

then you should call keepAlive on the FlowProcess.

**Comment by johnynek** [comment]
http://docs.cascading.org/cascading/2.0/javadoc/cascading/flow/hadoop/HadoopFlowProcess.html#keepAlive()

so, something like:
```scala

Execution.withId { implicit uid =>
  // now you can call:
  // RuntimeStats.getFlowProcessForUniqueId(uid).keepAlive
}
```

**Comment by ulyssepence** [comment]
@johnynek Oh, I was not familiar with this. Thanks. I'll close the issue for now.
