### ISSUE TITLE
Scalding 0.17.1 release proposal

### ISSUE THREAD

**Issue by piyushnarang** [twitter/scalding#1699]
We're thinking of cutting a 0.17.1 release to help cut a Summingbird release. We can pick up the tip of the 0.17.x branch: https://github.com/twitter/scalding/tree/0.17.x (and maybe include: https://github.com/twitter/scalding/pull/1667). 
Thoughts? @johnynek / @ttim / @pankajroark ?

**Comment by ttim** [comment]
I think it's a great idea. I believe 0.17.0 is broken for some cases (at least that what SB showed), and also SB 2.12 release is blocked on Scalding now.

**Comment by johnynek** [comment]
Sure I think that's great.

**Comment by piyushnarang** [comment]
Ok, great I'll get this rolling.

**Comment by tonyjzhou** [comment]
https://github.com/twitter/scalding/releases/tag/v0.17.1
