### ISSUE TITLE
0.17.1 broke binary compatibility

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1703]
https://github.com/twitter/scalding/blob/develop/build.sbt#L279

that should have been 0.17

Looks like ReducerEstimator was removed and replaced with Estimator.

0.17.1 should have been 0.18.0. We need to turn mima back on.

**Comment by piyushnarang** [comment]
It might be a good idea to turn this on in the travis CI build as well so that we get notified of it when putting out a PR.

**Comment by ttim** [comment]
`0.17.2` is out, backward compatible with `0.17.0`.
