### ISSUE TITLE
Make a function to convert a Job to an Execution

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1744]
I think we could have a function like:
```scala
def toExecution(c: Class[_ <: Job]): Execution[Unit]
```
which would work like a Job. If we had this, it could aid it converting more code to the execution API.

**Comment by ulyssepence** [comment]
@johnynek This is a good idea, one that I think we've discussed in the past. I'm trying to think what, if any, were the blockers in the past. @isnotinvain would probably know better than me.

**Comment by johnynek** [comment]
I think the blockers were that: 1) we didn't have a way to reset the config mid-execution, which Jobs need. 2) Job is kind of free-form in that it could be doing almost anything, so it might be unsafe in that who knows what methods were overriden.

So, if we can model `Job` as `Args, Mode, Class[_ <: Job] => (FlowDef, Option[Job])` we could be okay *if* we had something that allowed `FlowDef => Try[Execution[Unit]]`.

That second function could be done if we add to the FlowState all the typedpipe reads and writes, and if we only have typed-pipe reads and writes, then we can convert to `Execution[Unit]`, if not, the try fails. Or we could put the try inside the execution: `FlowDef => Execution[Unit]`.

**Comment by johnynek** [comment]
@benpence why don't you take a stab? I can help you make this PR. :)

**Comment by ulyssepence** [comment]
@johnynek OK I'll take a try in the beginning of next week

**Comment by ulyssepence** [comment]
> `Job` as `Args, Mode, Class[_ <: Job] => (FlowDef, Option[Job])`

What is the `Option[Job]` for?

> if we only have typed-pipe reads and writes

What else do we need to look out for here? You mean just arbitrary submitter-side code?

**Comment by johnynek** [comment]
there is `def next: Option[Job]` on a job. We could error if that is not empty, which is the vastly most common case (we could put the exception in the Execution of course).

**Comment by isnotinvain** [comment]
Ya I don't remember the blockers but this would be great to have. I feel like the fact that so much happens during the Job's constructor that that was part of the problem (eg you don't get to control when that gets executed) but I don't remember specifically what that'd break.

Even if we can't cover all cases this would still be useful.

**Comment by johnynek** [comment]
I implemented this: https://github.com/twitter/scalding/pull/1792 

Please review if you have time.
