### ISSUE TITLE
Nested mutation bug

### ISSUE THREAD

**Issue by fwbrasil** [twitter/scalding#1819]
I'm debugging a test that fails on the latest `develop` revision. `FlowStateMap.mutate` calls are nested and mutate the same `FlowDef`. The outer mutation overrides the mutations done by the nested call. Stack trace from the debugging session:

<img width="370" alt="screen shot 2018-02-20 at 1 37 37 pm" src="https://user-images.githubusercontent.com/831175/36454125-84f417d4-164f-11e8-8f2c-8dcc639f00c2.png">

Note the two `mutate` calls. 

Isolated example:

```scala
object NestedMutationBug extends App {
  implicit val fd = new FlowDef
  implicit val m = Local(false)
  val t = TypedPipe.from(TypedText.tsv[String]("")).write(NullSink)
  CascadingBackend.planTypedWrites(fd, m)
  val state = FlowStateMap.get(fd).get
  require(state.sourceMap.nonEmpty) // fails
}
```

**Comment by johnynek** [comment]
working on this now.
