### ISSUE TITLE
migrate to github CI

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1961]
There is no CI turned on at the moment.

cc: @nownikhil 

would you have time to set up github actions CI?

**Comment by johnynek** [comment]
I can give you some pointers:

https://github.com/djspiewak/sbt-github-actions

that plugin works rather well.

**Comment by johnynek** [comment]
see #1956

**Comment by nownikhil** [comment]
I am currently trying to finish some pending Beam runner issue. Either me or someone from scalding team will look at this.

**Comment by hazel-sudz** [comment]
@johnynek I could look into this if it's still open. I've been doing some tinkering with cacading4.5-WIP/hadoop3 just to see what's broken and would be helpful instead of waiting on local builds.

**Comment by johnynek** [comment]
As far as I know it is still open. I think the Twitter team has said they will look, but I guess they might not have prioritized it.

Note: I'm just a volunteer now. I don't use scalding myself and neither does my work. Also I don't have visibility inside Twitter and almost all my communication is via issues and PRs here so you know what I know. :)

**Comment by nownikhil** [comment]
@daniel-sudz Please have a look. This will be of huge help for us :)

**Comment by hazel-sudz** [comment]
sounds good thanks @johnynek @nownikhil 

just for context: I'm on a company using scalding that is trying to migrate to AWS EMR6 which requires a target of hadoop3. So I have some resources dedicating to exploring options within scalding to do so for the next couple months.

**Comment by johnynek** [comment]
BTW: I see there are being three approaches here now.

1. upgrade cascading for the entire project. We have attempted this before but found bugs in cascading which we had a hard time getting cascading project to address (I was told the bugs were from generated dags, not real dags, which I was confused by).
2. add a new subproject (like the scalding-beam or scalding-spark projects) to support cascading 3 or 4.
3. add a new subproject to directly run on Hadoop (don't go through cascading) similar to the above.

Since scalding has it's own optimizer and planner now, plans 2 and 3 might be nice ways to go (you can see the recent beam PRs to get an idea how much work it would be). I think running directly on Hadoop wouldn't be very hard now actually.

**Comment by hazel-sudz** [comment]
@nownikhil I have a draft at https://github.com/twitter/scalding/pull/1963 I still need to fix some small things though

**Comment by hazel-sudz** [comment]
https://github.com/twitter/scalding/pull/1963 is ready for review now
