### ISSUE TITLE
scalding-jbdc current use / discussion on support/deprecation

### ISSUE THREAD

**Issue by hazel-sudz** [twitter/scalding#1968]
I am wondering if there is still actual real use of the `scalding-jbdc` package in other orgs. My concern is that it pulls in a number of cascading ecosystem packages that are no longer supported (cascading-jdbc-core and cascading-jdbc-mysql). 

I see many years ago there was some activity on this: 

https://github.com/twitter/scalding/issues/1385
https://github.com/twitter/scalding/pull/1382

**Comment by johnynek** [comment]
@nownikhil can you comment?

Does Twitter object? IIRC twitter hasn't used that code in some time (I think there is an internal version).

**Comment by hazel-sudz** [comment]
I don't think we have usage at Foursquare @jonshea to confirm.

**Comment by jonshea** [comment]
Confirming that Foursquare does not use `scalding-jbdc`.

**Comment by hazel-sudz** [comment]
resolved by merge
