### ISSUE TITLE
Set up automatic publishing

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1973]
it would be really nice to set up automatic publishing as was done:

https://github.com/twitter/algebird/pull/867

this would enable a much faster cadence of release.

**Comment by hazel-sudz** [comment]
I can port a PR. Feel free to assign this to me. Would need someone to load the secrets into the github repo settings though but that would be a simple step independent of the actual workflow.

**Comment by johnynek** [comment]
this plugin is probably worth adopting:

https://github.com/typelevel/sbt-typelevel

I think it streamlines a lot of this and the maintainer is very helpful.

**Comment by hazel-sudz** [comment]
sbt-typelevel looks promising, looking into it. I'm usually weary of unnecessary dependencies but there's very high community support so seems fine to me.

**Comment by hazel-sudz** [comment]
I looked at sbt-typelevel and IMO is tries to do way too much. The generative aspect of the CI workflows makes it impossible to do any custom modifications and I don't think it's a good fit here. 

And we already have a workflow for running tests that works fine. I'm thinking of something like https://github.com/sbt/sbt-ci-release to handle just the release part separately. Don't see the value in re-organizing everything just to be able to use sbt-typelevel as a managed platform.

**Comment by hazel-sudz** [comment]
https://github.com/twitter/scalding/pull/1975 looking for someone to help with adding repo secrets for sonatype and GPG

**Comment by nownikhil** [comment]
I think I accidentally pushed the wrong commit in develop. Publish is failing. I think daniel pushed a commit as I did a squash and merge.

**Comment by hazel-sudz** [comment]
@nownikhil the commit seems fine to me. Publish is failing on GPG signing https://github.com/twitter/scalding/runs/5573979628?check_suite_focus=true

do we have GPG keys in the secrets section? That's probably the cause

**Comment by hazel-sudz** [comment]
you can see that the command passed to GPG does not include a passphrase: 

```
'gpg --batch --pinentry-mode loopback --passphrase  --detach-sign
```

typically it would read in the logs as 
```
'gpg --batch --pinentry-mode loopback --passphrase <****** redacted passphrase here in CI>  --detach-sign
```

**Comment by johnynek** [comment]
there are no secrets at all set up.

I am still an admin of this repo, so I can add them it seems.

**Comment by hazel-sudz** [comment]
~~@johnynek could would we consider publishing under the git namespace instead of `com.twitter`? For instance: `com.github.twitter.scalding`. This allows us to bypass the domain verification requirement of sonatype~~

edit: I misread we would need to have repo creation rights 

https://central.sonatype.org/faq/verify-ownership/#answer
```
If you are registering a group ID based on your SCM host (such as Github, Bitbucket, Gitee, etc), 
we will ask that you create a publicly accessible repository that is named after your JIRA ticket number (such as OSSRH-00000 in the example above). 
This will help us verify that you control your source code repository. This repository can also be deleted after we have verified and setup your project.
```

it seems like getting sonatype creds for the root twitter domain is a dead end for now

**Comment by johnynek** [comment]
sorry, @daniel-sudz I have slept on this... I am going to try to set this up this weekend.

**Comment by johnynek** [comment]
okay, I have added the four needed secrets I think.

I have added my personal login to sonatype, which I believe still has the rights to publish. We will see!

So, I guess we can make a kind of no-op push and see if it publishes. @daniel-sudz do you want to try that?

**Comment by hazel-sudz** [comment]
@johnynek it's all good :) 
yeah let's test it, completely possible that some things need to tweaked if it fails I can follow up on that

**Comment by hazel-sudz** [comment]
https://github.com/twitter/scalding/pull/1984

**Comment by hazel-sudz** [comment]
v2 attempt: https://github.com/twitter/scalding/pull/1985

**Comment by johnynek** [comment]
I think this was done.
