### ISSUE TITLE
scalding-hadoop3 backend OR spark backend upgrade to 3.X

### ISSUE THREAD

**Issue by hazel-sudz** [twitter/scalding#1974]
**Is your feature request related to a problem? Please describe.**
For the use cases that @jonshea and I need, we require hadoop3 or spark3. It doesn't matter which one but he have a managed runtime (AWS EMR) that forces us to use newer versions of either. 

**Describe the solution you'd like**
We would like to either: 

1. upgrade the existing spark-backed to spark3.X and scala 2.12
2. if 1 is not possible then we would like to write a hadoop backend that will use hadoop3.

**Questions**
Who uses the spark backend? What was it written for and is in production anywhere? Can we upgrade it or will it be problematic?

**Comment by johnynek** [comment]
I am not aware of anyone who would be broken by this.

To be clear: I think a spark backend is easier to implement that Hadoop, because Hadoop is lower level. That said, I haven't looked at Hadoop 3 and once upon a time, Tez promised to be a reasonable target for these jobs. I don't know if it is reliable, or the core MapReduce api has more primitives (e.g. map->reduce->reduce....).

But Hadoop brings a smaller dependency tree in and doesn't tie you to a specific version of scala, so that may be a value.

I think we should be able to upgrade the spark backend (and freshen it up by migrating to Dataset vs RDD).

**Comment by nownikhil** [comment]
+1 to experimenting with Dataset API.

I wonder if it would make sense to explore SQL capabilities on TypedPipe. This is equivalent to Dataframe API in Spark, also many data processing systems like Beam, Flink, Spark support both Typed & Untyped APIs.

**Comment by hazel-sudz** [comment]
I am curious on the potential performance of a TEZ implementation. If I understand correctly a typedPipe is already a DAG structure so it is more "native" in the sense that operations can be more logically mapped. 

@johnynek you mentioned reliability and I think this is no longer a major concern. It seems like many projects are now favoring TEZ over MR such as hive: https://issues.apache.org/jira/browse/HIVE-12300

**Comment by johnynek** [comment]
I think it would be competitive with spark. It would be very interesting to see. I agree it is likely a better fit. I'm happy to help review and sketch ideas for how to go about it.

Do you know of a list of operations in Tex or a concise summary of the API?

**Comment by hazel-sudz** [comment]
> I think it would be competitive with spark. It would be very interesting to see. I agree it is likely a better fit. I'm happy to help review and sketch ideas for how to go about it.
> 
> Do you know of a list of operations in Tex or a concise summary of the API?

I am still trying to get up to speed on TEZ in general and grokking how the existing spark/beam backends are structured in scalding. I will try to get some kind of document in the next couple of days including all the info that I have. I'm currently planning on exploring https://github.com/apache/tez/tree/master/tez-examples/src/main/java/org/apache/tez/examples and maybe doing some example jobs to explore functionaility.

I will aim for a follow-up likely next Monday. Would that work?

**Comment by johnynek** [comment]
I think those examples cover all the core operations actually. Maybe a first step is getting something to run in a unit test, then you can easily add tests for the simplest to most complex jobs.

**Comment by hazel-sudz** [comment]
how would you handle dynamic aspects of the DAG? For instance in TEZ processors for vertices are specified using a string to refer to the classname (there is no automatic dynamic serialization magic such as what spark performs on lambdas from what I can tell). 

for an operation such as `map`, would we serialize the mapping function itself and inject it on the processor class? I see there's already some Kryo usage

**Comment by johnynek** [comment]
Yeah. The same strategy as spark and cascading honestly. You serialize the function put it in the config as base64 encoded value then deserialize in the task. This way you only have a few task classes.

**Comment by hazel-sudz** [comment]
interesting, in poorly designed user code this could blow up the size of the config. Never really though of this... anyways thanks for confirming :)

**Comment by johnynek** [comment]
With gzip + use of references in Kryo in practice it usually isn't a problem. An alternate is to serialize it to HDFS which cascading does if it is too large.

**Comment by hazel-sudz** [comment]
> Yeah. The same strategy as spark and cascading honestly. You serialize the function put it in the config as base64 encoded value then deserialize in the task. This way you only have a few task classes.

ok I think that part I figured out. What about the key/value objects that are coming from the tuple input. Do those always get serialized to a bytestream when writing output? I'll take a look at how cascading/scalding does it when writing to hadoop output.

**Comment by johnynek** [comment]
Hadoop has a key/value model. So cascading puts things in these Tuple objects (which scalding.typed really doesn't use) and then breaks part of the tuple into a key and part into a value.

For groupBy operations, the scalding key would be put into the hadoop key and likewise for the value.

For map only operations or reduce operations that have a trailing map, you have to decide: you can put all in key or value and basically use unit (I think Hadoop refers to this as void following Java) values.

For spark dataset: again it can manage this.

Lastly: you do have to use the Ordering you get for the sort partitioning in Hadoop and if you use OrderedSerialization, you need to handle that specially as well (the Beam code has an example of this, but I'm on my phone).
