### ISSUE TITLE
Re-enable code coverage

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1977]
https://github.com/twitter/scalding/pull/1922

that PR was started, but went stale.

I don't think it is much work.

@daniel-sudz @nownikhil

**Comment by hazel-sudz** [comment]
@johnynek I can look into this next week. We are also still waiting on the situation with publishing keys for sonatype and GPG

**Comment by hazel-sudz** [comment]
they have a binding for github-actions that is credential-less: https://github.com/marketplace/actions/codecov
I will try to get something out today

**Comment by hazel-sudz** [comment]
I think we need more aggressive timeouts on the codecov uploader. Based on what I've seen in https://github.com/codecov/codecov-action/issues the symptom seems to be hitting github rate limits on their API. 

Another resolution for some people appears to be adding an auth token. This is optional for public repos, but seems to help some people to not get upload failures.
