### ISSUE TITLE
copy dagon into this tree

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1978]
https://github.com/stripe/dagon

Dagon was extracted from summingbird since we wanted to use it in scalding, but having a separate repo is inconvenient.

We should copy that code back here and move the package name to `com.twitter.scalding.dagon`.

This reduces external dependencies and challenges in maintaining.

**Comment by hazel-sudz** [comment]
I'm fine with doing this, seems pretty mechanical. 

I would like to see some organization/splitting on the `build.sbt` file though just shoving everything in the root file is getting unwieldy. From just glancing at the docs I think a subproject `build.sbt` file should work
