### ISSUE TITLE
push new tags

### ISSUE THREAD

**Issue by hazel-sudz** [twitter/scalding#1995]
The last tag push happened before we fixed the publishing situation. It seems like my company's build doesn't like SNAPSHOT artifacts and I would like to test some things with recent changes in the spark backend.

If it's not too much of a hassle any chance someone could please push an `0.18.0-RC3` tag off develop? Sorry for pinging but @johnynek would be much appreciated :)

**Comment by johnynek** [comment]
https://github.com/twitter/scalding/tree/v0.18.0-RC3

done.

**Comment by hazel-sudz** [comment]
thanks I need to switch the trigger to be tags not release though. A release is a tag but a tag is not a release apparently. Also some strange CI failures from cascading on the recent push `failure to get lock on filesystem` I will take a look but I've never seen it before

**Comment by hazel-sudz** [comment]
```
rror] Test com.twitter.scalding.commons.datastores.VersionedStoreTest.testCleanup failed: java.lang.RuntimeException: java.io.IOException: failure to login
[error]     at com.twitter.scalding.commons.datastores.FSTestCase.<init>(FSTestCase.java:17)
[error]     at com.twitter.scalding.commons.datastores.VersionedStoreTest.<init>(VersionedStoreTest.java:13)
[error]     ...
```

```
[info] - should read c0 and clobber c1 *** FAILED ***
[info]   cascading.flow.planner.PlannerException: could not build flow from assembly: [unable to get handle to underlying filesystem]
[info]   at cascading.flow.planner.FlowPlanner.handleExceptionDuringPlanning(FlowPlanner.java:578)
[info]   at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:286)
[info]   at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:80)
```

first time seeing these two.

**Comment by hazel-sudz** [comment]
> thanks I need to switch the trigger to be tags not release though. A release is a tag but a tag is not a release apparently. Also some strange CI failures from cascading on the recent push `failure to get lock on filesystem` I will take a look but I've never seen it before

I can either switch the trigger or we can use "create release from tag" and keep the existing trigger. Let me know which one is preferred. Thanks again
