### ISSUE TITLE
Make TypedPipe referentially transparent

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#936]
Even though TypedPipe *looks* like it is a nice, pure, functional API, it is not. .write mutates a FlowDef that comes and assumes the head of that pipe has been sourced in that FlowDef. An alternate strategy is used by cascalog, which we almost have the code in place to copy: the TypedPipe should hold a local view of the FlowDef needed to run it. We never mutate that FlowDef, and it is private. When .toPipe or .write is called, the local FlowDef is merged into the target FlowDef. In this way, TypedPipe stays immutable, and referentially transparent.

You could even share TypedPipes between jobs.

This becomes more concerning when you try to use ExecutionContext and imagine returning a TypedPipe from one job, and using that in the next, which might not be uncommon.

The main thing to get right here is an idempotent mergeFrom on RichFlowDef. We also should have lots of tests on this code as it would change, pretty fundamentally, the way the code worked.

All this said, I don't think it has to change the source code compatibility at all. Only implicit parameters would change, and only in a few places.

@bholt might be a good candidate here.

**Comment by johnynek** [comment]
fixed by #968

**Comment by bholt** [comment]
Nice!
