### ISSUE TITLE
Add support for writing case classes to sinks

### ISSUE THREAD

**Issue by danosipov** [twitter/scalding#939]
I was trying to test the Typed API pipeline, and ran into an error, where I wasn't able to write a TypedPipe with a case class. I followed documentation for setting up the TypedPipe, but if I made an error, let me know.

I was able to get it to work by mapping the case class back to tuples.

Here is a faling test case:
```
object TwoInts {
  def fromTuple(t: (Int, Int)): TwoInts = TwoInts(t._1, t._2)
}

case class TwoInts(int1: Int, int2: Int) {
  def toTuple: (Int, Int) = (int1, int2)
}

class TypedCaseJob(args: Args) extends Job(args) {
  TextLine("inputFile")
    .read
    .mapTo('one, 'two) { line: String => line.split("\\:") }
    .toTypedPipe[(Int, Int)]('one, 'two)
    .map(TwoInts.fromTuple(_))
    .write(TypedTsv[TwoInts]("outputFile"))
}

class TypedCaseTest extends Specification {
  import Dsl._
  noDetailedDiffs()
  "A TypedPipe" should {
    TUtil.printStack {
      JobTest(new com.twitter.scalding.TypedCaseJob(_))
        .source(TextLine("inputFile"), List("0" -> "1:2"))
        .sink[(String, Long)](TypedTsv[(String, Long)]("outputFile")){ outputBuffer =>
          "write case classes" in {
            outputBuffer.size must be_==(1)
          }
        }
        .run
        .finish
    }
  }
}
```

Error:
```
Failed to create a tap for: FixedPathTypedDelimited(List(outputFile),0,false,false,	,com.twitter.scalding.TwoInts) (package.scala:27)
```

**Comment by johnynek** [comment]
We have an internal version of this using macros now. Should release.

We just use TypeDescriptor and plumb it through, then you import the TypeDescriptor provider macro.

**Comment by dvxam** [comment]
Some news on this? @danosipov

**Comment by isnotinvain** [comment]
This does exist now: 
https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/source/TypedText.scala

It supports tuples and case classes, using macros.
